# Generated by Django 4.0.3 on 2022-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
