# Generated by Django 4.0.3 on 2022-03-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0003_alter_song_genre_alter_song_length_alter_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
