# Generated by Django 4.1 on 2022-08-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0009_playlist_rename_song_track_playlisttrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musiclibrary.album'),
        ),
    ]
